#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIETHERNET_NUM_INSTANCES 1

/* Definitions for peripheral AXI_ETHERNET_0 */
#define XPAR_AXI_ETHERNET_0_COMPATIBLE "xlnx,axi-ethernet-7.2"
#define XPAR_AXI_ETHERNET_0_BASEADDR 0x40c00000
#define XPAR_AXI_ETHERNET_0_HIGHADDR 0x40c3ffff
#define XPAR_AXI_ETHERNET_0_TXCSUM 0x0
#define XPAR_AXI_ETHERNET_0_RXCSUM 0x0
#define XPAR_AXI_ETHERNET_0_PHY_MODE "mii"
#define XPAR_AXI_ETHERNET_0_STATISTICS_COUNTERS 0x1
#define XPAR_AXI_ETHERNET_0_SPEED_1_2P5 0x3e8
#define XPAR_AXI_ETHERNET_0_NUMBER_OF_TABLE_ENTRIES 0x0
#define XPAR_AXI_ETHERNET_0_PHYADDR 0x1
#define XPAR_AXI_ETHERNET_0_AXISTREAM_CONNECTED 0x44a00001

/* Canonical definitions for peripheral AXI_ETHERNET_0 */
#define XPAR_XAXIETHERNET_0_BASEADDR 0x40c00000
#define XPAR_XAXIETHERNET_0_HIGHADDR 0x40c3ffff
#define XPAR_XAXIETHERNET_0_AXISTREAM_CONNECTED 0x44a00001
#define XPAR_XAXIETHERNET_0_COMPATIBLE "xlnx,axi-ethernet-7.2"
#define XPAR_XAXIETHERNET_0_NUMBER_OF_TABLE_ENTRIES 0x0
#define XPAR_XAXIETHERNET_0_PHY_MODE "mii"
#define XPAR_XAXIETHERNET_0_PHYADDR 0x1
#define XPAR_XAXIETHERNET_0_RXCSUM 0x0
#define XPAR_XAXIETHERNET_0_STATISTICS_COUNTERS 0x1
#define XPAR_XAXIETHERNET_0_SPEED_1_2P5 0x3e8
#define XPAR_XAXIETHERNET_0_TXCSUM 0x0

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x1ffff
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x1ffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral AXI_GPIO_BUTTONS */
#define XPAR_AXI_GPIO_BUTTONS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_BUTTONS_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_BUTTONS_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_BUTTONS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_BUTTONS_IS_DUAL 0x0
#define XPAR_AXI_GPIO_BUTTONS_GPIO_WIDTH 0x5

/* Canonical definitions for peripheral AXI_GPIO_BUTTONS */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x5
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_LEDS */
#define XPAR_AXI_GPIO_LEDS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_LEDS_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_LEDS_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_LEDS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_LEDS_IS_DUAL 0x0
#define XPAR_AXI_GPIO_LEDS_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_LEDS */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x10
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_SWITCHES */
#define XPAR_AXI_GPIO_SWITCHES_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_SWITCHES_BASEADDR 0x40020000
#define XPAR_AXI_GPIO_SWITCHES_HIGHADDR 0x4002ffff
#define XPAR_AXI_GPIO_SWITCHES_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_SWITCHES_IS_DUAL 0x0
#define XPAR_AXI_GPIO_SWITCHES_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_SWITCHES */
#define XPAR_XGPIO_2_BASEADDR 0x40020000
#define XPAR_XGPIO_2_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x10
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_I2C */
#define XPAR_AXI_I2C_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_AXI_I2C_BASEADDR 0x40800000
#define XPAR_AXI_I2C_HIGHADDR 0x4080ffff
#define XPAR_AXI_I2C_TEN_BIT_ADR 0x0
#define XPAR_AXI_I2C_GPO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_I2C */
#define XPAR_XIIC_0_BASEADDR 0x40800000
#define XPAR_XIIC_0_HIGHADDR 0x4080ffff
#define XPAR_XIIC_0_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_XIIC_0_GPO_WIDTH 0x1
#define XPAR_XIIC_0_TEN_BIT_ADR 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0x3
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_SW_INTR 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_IVR 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_CIE 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_SIE 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HAS_IPR 0x1

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x3
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XLLFIFO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_ETHERNET_0_FIFO */
#define XPAR_AXI_ETHERNET_0_FIFO_COMPATIBLE "xlnx,axi-fifo-mm-s-4.3"
#define XPAR_AXI_ETHERNET_0_FIFO_BASEADDR 0x44a00000
#define XPAR_AXI_ETHERNET_0_FIFO_HIGHADDR 0x44a0ffff
#define XPAR_AXI_ETHERNET_0_FIFO_DATA_INTERFACE_TYPE 0x0

/* Canonical definitions for peripheral AXI_ETHERNET_0_FIFO */
#define XPAR_XLLFIFO_0_BASEADDR 0x44a00000
#define XPAR_XLLFIFO_0_HIGHADDR 0x44a0ffff
#define XPAR_XLLFIFO_0_COMPATIBLE "xlnx,axi-fifo-mm-s-4.3"
#define XPAR_XLLFIFO_0_DATA_INTERFACE_TYPE 0x0

#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral AXI_QUAD_SPI */
#define XPAR_AXI_QUAD_SPI_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_BASEADDR 0x44a20000
#define XPAR_AXI_QUAD_SPI_HIGHADDR 0x44a2ffff
#define XPAR_AXI_QUAD_SPI_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_FIFO_SIZE 0x10

/* Canonical definitions for peripheral AXI_QUAD_SPI */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a20000
#define XPAR_XSPI_0_HIGHADDR 0x44a2ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x10
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x0
#define XPAR_XSPI_0_XIP_MODE 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral AXI_CUSTOM_AES_ACCEL */
#define XPAR_AXI_CUSTOM_AES_ACCEL_BASEADDR 0x44a10000
#define XPAR_AXI_CUSTOM_AES_ACCEL_HIGHADDR 0x44a1ffff

/* Canonical definitions for peripheral AXI_CUSTOM_AES_ACCEL */
#define XPAR_AXI_CUSTOM_AES_128_ACCEL_0_BASEADDR 0x44a10000
#define XPAR_AXI_CUSTOM_AES_128_ACCEL_0_HIGHADDR 0x44a1ffff

/*  BOARD definition */
#define XPS_BOARD_NEXYS-A7-100T

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_RISCV_FREQ 100000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */