domain_path: /home/miguelovila/Documents/siae-project-aes128-iot-gw/aes_128_iot_gw/platform2/export/platform2/sw/freertos_microblaze_0
app_src_dir: /opt/xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/freertos_lwip_echo_server
template: freertos_lwip_echo_server
lang: c
